#!/usr/bin/env ruby

require "optparse"
require_relative "../lib/pump/project_generator"
require_relative "../lib/pump/server"
require_relative "../lib/handcar/version"

options = {
  action: ARGV.shift
}

OptionParser.new { |opts|
  opts.banner = "Usage: handcar [options]"

  opts.on("-v", "--[no-]verbose", "Print the current version") do |v|
    options[:action] = "version"
  end
}.parse!

case options[:action]
when "new"
  options[:path] = ARGV.shift
  ProjectGenerator.new(options[:path]).generate
when "version"
  puts Handcar::VERSION
when "serve", "s"
  Handcar::Server.new(options).serve
end
